bt_navigator:
  ros__parameters:
    use_sim_time: false
    default_nav_to_pose_bt_xml: "/home/ubuntu/ros2_ws/src/navigate_to_pose_w_replanning_and_recovery.xml"
    default_nav_through_poses_bt_xml: "/home/ubuntu/ros2_ws/src/navigate_through_poses_w_replanning_and_recovery.xml"
